# Generated by Django 3.2 on 2021-07-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=19, null=True),
        ),
    ]
